import { type Language } from "@/types";

export const siteConfig = {
  name: "code_guess",
};

export const MAX_TRIES = 6;

export const languages: Language[] = [
  {
    name: "JavaScript",
    paradigm: ["Object-oriented", "Functional", "Event-driven"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Brendan Eich",
    firstAppeared: 1995,
    mainUseCase: "Web",
  },
  {
    name: "Python",
    paradigm: ["Object-oriented", "Functional", "Imperative"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Guido van Rossum",
    firstAppeared: 1991,
    mainUseCase: "General-purpose",
  },
  {
    name: "Rust",
    paradigm: ["Multi-paradigm", "Concurrent"],
    typing: "Static",
    garbageCollection: false,
    designedBy: "Graydon Hoare",
    firstAppeared: 2010,
    mainUseCase: "Systems",
  },
  {
    name: "Go",
    paradigm: ["Concurrent", "Imperative", "Structured"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "Robert Griesemer, Rob Pike, Ken Thompson",
    firstAppeared: 2009,
    mainUseCase: "Systems",
  },
  {
    name: "TypeScript",
    paradigm: ["Object-oriented", "Functional"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "Anders Hejlsberg",
    firstAppeared: 2012,
    mainUseCase: "Web",
  },
  {
    name: "C",
    paradigm: ["Procedural", "Structured"],
    typing: "Static",
    garbageCollection: false,
    designedBy: "Dennis Ritchie",
    firstAppeared: 1972,
    mainUseCase: "Systems",
  },
  {
    name: "C++",
    paradigm: ["Object-oriented", "Procedural", "Generic"],
    typing: "Static",
    garbageCollection: false,
    designedBy: "Bjarne Stroustrup",
    firstAppeared: 1985,
    mainUseCase: "General-purpose",
  },
  {
    name: "Java",
    paradigm: ["Object-oriented", "Structured"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "James Gosling",
    firstAppeared: 1995,
    mainUseCase: "Enterprise",
  },
  {
    name: "C#",
    paradigm: ["Object-oriented", "Component-oriented"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "Microsoft",
    firstAppeared: 2000,
    mainUseCase: "Enterprise",
  },
  {
    name: "Swift",
    paradigm: ["Object-oriented", "Functional", "Protocol-oriented"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "Apple Inc.",
    firstAppeared: 2014,
    mainUseCase: "iOS Development",
  },
  {
    name: "Kotlin",
    paradigm: ["Object-oriented", "Functional"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "JetBrains",
    firstAppeared: 2011,
    mainUseCase: "Android Development",
  },
  {
    name: "PHP",
    paradigm: ["Object-oriented", "Imperative"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Rasmus Lerdorf",
    firstAppeared: 1995,
    mainUseCase: "Web",
  },
  {
    name: "Ruby",
    paradigm: ["Object-oriented", "Reflective"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Yukihiro Matsumoto",
    firstAppeared: 1995,
    mainUseCase: "Web",
  },
  {
    name: "Perl",
    paradigm: ["Multi-paradigm"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Larry Wall",
    firstAppeared: 1987,
    mainUseCase: "Scripting",
  },
  {
    name: "Haskell",
    paradigm: ["Functional"],
    typing: "Static",
    garbageCollection: true,
    designedBy: "Simon Peyton Jones, Paul Hudak, Philip Wadler",
    firstAppeared: 1990,
    mainUseCase: "Academic",
  },
  {
    name: "Lisp",
    paradigm: ["Functional", "Meta"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "John McCarthy",
    firstAppeared: 1958,
    mainUseCase: "AI",
  },
  {
    name: "Lua",
    paradigm: ["Procedural", "Functional", "Data-driven"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Roberto Ierusalimschy",
    firstAppeared: 1993,
    mainUseCase: "Embedded scripting",
  },
  {
    name: "R",
    paradigm: ["Functional", "Procedural"],
    typing: "Dynamic",
    garbageCollection: true,
    designedBy: "Ross Ihaka, Robert Gentleman",
    firstAppeared: 1993,
    mainUseCase: "Statistical computing",
  },
];
